void importMatrix ();
void initResources ();
void sendOperations();
void printMatrix();
void freeResources();
void createSons();
pthread_mutex_t *getMutexA();
pthread_mutex_t *getMutexB();
pthread_mutex_t *getMutexC();
pthread_mutex_t *getMutexSum();
int* getMemA();
int* getMemB();
int* getMemC();
int* getMemSum();	
int getOrder();
